version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: "gestion-stages-web"
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: "gestion-stages-db"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestion_stages
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
